---
- name: Install package
  package:
    name:
      - 'certbot'
      - 'python3-certbot'
      - 'python3-certbot-dns-route53'
    state: latest

- name: Create aws config directory
  ansible.builtin.file:
    path: ~/.aws/
    state: directory
    mode: '0700'

- name: Generate aws config file from template
  template:
    src: 'config.j2'
    dest: ~/.aws/config
    mode: u=rw,g=r,o=r

- name: Generate cli.ini file from template
  template:
    src: 'cli.ini.j2'
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate certbot.service file from template
  template:
    src: 'certbot.service.j2'
    dest: /etc/systemd/system/certbot.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate certbot.timer file from template
  template:
    src: 'certbot.timer.j2'
    dest: /etc/systemd/system/certbot.timer
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ host_fqdn }}/cert.pem
  register: letsencrypt_cert

- name: Create certificate
  shell: |
    certbot certonly --non-interactive --dns-route53 --domains {{ host_fqdn }}
  when: not letsencrypt_cert.stat.exists

- name: Enable daemon
  service:
    name: certbot.timer
    daemon_reload: true
    enabled: yes
    state: started